// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_message_2eproto;
namespace messaging {
class EKF_msg;
struct EKF_msgDefaultTypeInternal;
extern EKF_msgDefaultTypeInternal _EKF_msg_default_instance_;
class IMU_msg;
struct IMU_msgDefaultTypeInternal;
extern IMU_msgDefaultTypeInternal _IMU_msg_default_instance_;
class Quaternion_msg;
struct Quaternion_msgDefaultTypeInternal;
extern Quaternion_msgDefaultTypeInternal _Quaternion_msg_default_instance_;
class Vector3_msg;
struct Vector3_msgDefaultTypeInternal;
extern Vector3_msgDefaultTypeInternal _Vector3_msg_default_instance_;
class Vicon_msg;
struct Vicon_msgDefaultTypeInternal;
extern Vicon_msgDefaultTypeInternal _Vicon_msg_default_instance_;
}  // namespace messaging
PROTOBUF_NAMESPACE_OPEN
template<> ::messaging::EKF_msg* Arena::CreateMaybeMessage<::messaging::EKF_msg>(Arena*);
template<> ::messaging::IMU_msg* Arena::CreateMaybeMessage<::messaging::IMU_msg>(Arena*);
template<> ::messaging::Quaternion_msg* Arena::CreateMaybeMessage<::messaging::Quaternion_msg>(Arena*);
template<> ::messaging::Vector3_msg* Arena::CreateMaybeMessage<::messaging::Vector3_msg>(Arena*);
template<> ::messaging::Vicon_msg* Arena::CreateMaybeMessage<::messaging::Vicon_msg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace messaging {

// ===================================================================

class EKF_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messaging.EKF_msg) */ {
 public:
  inline EKF_msg() : EKF_msg(nullptr) {}
  ~EKF_msg() override;
  explicit constexpr EKF_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EKF_msg(const EKF_msg& from);
  EKF_msg(EKF_msg&& from) noexcept
    : EKF_msg() {
    *this = ::std::move(from);
  }

  inline EKF_msg& operator=(const EKF_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline EKF_msg& operator=(EKF_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EKF_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const EKF_msg* internal_default_instance() {
    return reinterpret_cast<const EKF_msg*>(
               &_EKF_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EKF_msg& a, EKF_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(EKF_msg* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EKF_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EKF_msg* New() const final {
    return new EKF_msg();
  }

  EKF_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EKF_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EKF_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const EKF_msg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EKF_msg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messaging.EKF_msg";
  }
  protected:
  explicit EKF_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kQuaternionFieldNumber = 2,
    kVelocityFieldNumber = 3,
    kAccelerationBiasFieldNumber = 4,
    kAngularVelocityBiasFieldNumber = 5,
    kTimeFieldNumber = 6,
  };
  // .messaging.Vector3_msg position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::messaging::Vector3_msg& position() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Vector3_msg* release_position();
  ::messaging::Vector3_msg* mutable_position();
  void set_allocated_position(::messaging::Vector3_msg* position);
  private:
  const ::messaging::Vector3_msg& _internal_position() const;
  ::messaging::Vector3_msg* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::messaging::Vector3_msg* position);
  ::messaging::Vector3_msg* unsafe_arena_release_position();

  // .messaging.Quaternion_msg quaternion = 2;
  bool has_quaternion() const;
  private:
  bool _internal_has_quaternion() const;
  public:
  void clear_quaternion();
  const ::messaging::Quaternion_msg& quaternion() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Quaternion_msg* release_quaternion();
  ::messaging::Quaternion_msg* mutable_quaternion();
  void set_allocated_quaternion(::messaging::Quaternion_msg* quaternion);
  private:
  const ::messaging::Quaternion_msg& _internal_quaternion() const;
  ::messaging::Quaternion_msg* _internal_mutable_quaternion();
  public:
  void unsafe_arena_set_allocated_quaternion(
      ::messaging::Quaternion_msg* quaternion);
  ::messaging::Quaternion_msg* unsafe_arena_release_quaternion();

  // .messaging.Vector3_msg velocity = 3;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::messaging::Vector3_msg& velocity() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Vector3_msg* release_velocity();
  ::messaging::Vector3_msg* mutable_velocity();
  void set_allocated_velocity(::messaging::Vector3_msg* velocity);
  private:
  const ::messaging::Vector3_msg& _internal_velocity() const;
  ::messaging::Vector3_msg* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::messaging::Vector3_msg* velocity);
  ::messaging::Vector3_msg* unsafe_arena_release_velocity();

  // .messaging.Vector3_msg acceleration_bias = 4;
  bool has_acceleration_bias() const;
  private:
  bool _internal_has_acceleration_bias() const;
  public:
  void clear_acceleration_bias();
  const ::messaging::Vector3_msg& acceleration_bias() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Vector3_msg* release_acceleration_bias();
  ::messaging::Vector3_msg* mutable_acceleration_bias();
  void set_allocated_acceleration_bias(::messaging::Vector3_msg* acceleration_bias);
  private:
  const ::messaging::Vector3_msg& _internal_acceleration_bias() const;
  ::messaging::Vector3_msg* _internal_mutable_acceleration_bias();
  public:
  void unsafe_arena_set_allocated_acceleration_bias(
      ::messaging::Vector3_msg* acceleration_bias);
  ::messaging::Vector3_msg* unsafe_arena_release_acceleration_bias();

  // .messaging.Vector3_msg angular_velocity_bias = 5;
  bool has_angular_velocity_bias() const;
  private:
  bool _internal_has_angular_velocity_bias() const;
  public:
  void clear_angular_velocity_bias();
  const ::messaging::Vector3_msg& angular_velocity_bias() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Vector3_msg* release_angular_velocity_bias();
  ::messaging::Vector3_msg* mutable_angular_velocity_bias();
  void set_allocated_angular_velocity_bias(::messaging::Vector3_msg* angular_velocity_bias);
  private:
  const ::messaging::Vector3_msg& _internal_angular_velocity_bias() const;
  ::messaging::Vector3_msg* _internal_mutable_angular_velocity_bias();
  public:
  void unsafe_arena_set_allocated_angular_velocity_bias(
      ::messaging::Vector3_msg* angular_velocity_bias);
  ::messaging::Vector3_msg* unsafe_arena_release_angular_velocity_bias();

  // double time = 6;
  void clear_time();
  double time() const;
  void set_time(double value);
  private:
  double _internal_time() const;
  void _internal_set_time(double value);
  public:

  // @@protoc_insertion_point(class_scope:messaging.EKF_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::messaging::Vector3_msg* position_;
  ::messaging::Quaternion_msg* quaternion_;
  ::messaging::Vector3_msg* velocity_;
  ::messaging::Vector3_msg* acceleration_bias_;
  ::messaging::Vector3_msg* angular_velocity_bias_;
  double time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class IMU_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messaging.IMU_msg) */ {
 public:
  inline IMU_msg() : IMU_msg(nullptr) {}
  ~IMU_msg() override;
  explicit constexpr IMU_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IMU_msg(const IMU_msg& from);
  IMU_msg(IMU_msg&& from) noexcept
    : IMU_msg() {
    *this = ::std::move(from);
  }

  inline IMU_msg& operator=(const IMU_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline IMU_msg& operator=(IMU_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IMU_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const IMU_msg* internal_default_instance() {
    return reinterpret_cast<const IMU_msg*>(
               &_IMU_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IMU_msg& a, IMU_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(IMU_msg* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IMU_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline IMU_msg* New() const final {
    return new IMU_msg();
  }

  IMU_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<IMU_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IMU_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const IMU_msg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IMU_msg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messaging.IMU_msg";
  }
  protected:
  explicit IMU_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccelerationFieldNumber = 1,
    kGyroscopeFieldNumber = 2,
    kTimeFieldNumber = 3,
  };
  // .messaging.Vector3_msg acceleration = 1;
  bool has_acceleration() const;
  private:
  bool _internal_has_acceleration() const;
  public:
  void clear_acceleration();
  const ::messaging::Vector3_msg& acceleration() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Vector3_msg* release_acceleration();
  ::messaging::Vector3_msg* mutable_acceleration();
  void set_allocated_acceleration(::messaging::Vector3_msg* acceleration);
  private:
  const ::messaging::Vector3_msg& _internal_acceleration() const;
  ::messaging::Vector3_msg* _internal_mutable_acceleration();
  public:
  void unsafe_arena_set_allocated_acceleration(
      ::messaging::Vector3_msg* acceleration);
  ::messaging::Vector3_msg* unsafe_arena_release_acceleration();

  // .messaging.Vector3_msg gyroscope = 2;
  bool has_gyroscope() const;
  private:
  bool _internal_has_gyroscope() const;
  public:
  void clear_gyroscope();
  const ::messaging::Vector3_msg& gyroscope() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Vector3_msg* release_gyroscope();
  ::messaging::Vector3_msg* mutable_gyroscope();
  void set_allocated_gyroscope(::messaging::Vector3_msg* gyroscope);
  private:
  const ::messaging::Vector3_msg& _internal_gyroscope() const;
  ::messaging::Vector3_msg* _internal_mutable_gyroscope();
  public:
  void unsafe_arena_set_allocated_gyroscope(
      ::messaging::Vector3_msg* gyroscope);
  ::messaging::Vector3_msg* unsafe_arena_release_gyroscope();

  // double time = 3;
  void clear_time();
  double time() const;
  void set_time(double value);
  private:
  double _internal_time() const;
  void _internal_set_time(double value);
  public:

  // @@protoc_insertion_point(class_scope:messaging.IMU_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::messaging::Vector3_msg* acceleration_;
  ::messaging::Vector3_msg* gyroscope_;
  double time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Vicon_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messaging.Vicon_msg) */ {
 public:
  inline Vicon_msg() : Vicon_msg(nullptr) {}
  ~Vicon_msg() override;
  explicit constexpr Vicon_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vicon_msg(const Vicon_msg& from);
  Vicon_msg(Vicon_msg&& from) noexcept
    : Vicon_msg() {
    *this = ::std::move(from);
  }

  inline Vicon_msg& operator=(const Vicon_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vicon_msg& operator=(Vicon_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vicon_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vicon_msg* internal_default_instance() {
    return reinterpret_cast<const Vicon_msg*>(
               &_Vicon_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Vicon_msg& a, Vicon_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(Vicon_msg* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vicon_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vicon_msg* New() const final {
    return new Vicon_msg();
  }

  Vicon_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vicon_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vicon_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Vicon_msg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vicon_msg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messaging.Vicon_msg";
  }
  protected:
  explicit Vicon_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kQuaternionFieldNumber = 2,
    kTimeFieldNumber = 3,
  };
  // .messaging.Vector3_msg position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::messaging::Vector3_msg& position() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Vector3_msg* release_position();
  ::messaging::Vector3_msg* mutable_position();
  void set_allocated_position(::messaging::Vector3_msg* position);
  private:
  const ::messaging::Vector3_msg& _internal_position() const;
  ::messaging::Vector3_msg* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::messaging::Vector3_msg* position);
  ::messaging::Vector3_msg* unsafe_arena_release_position();

  // .messaging.Quaternion_msg quaternion = 2;
  bool has_quaternion() const;
  private:
  bool _internal_has_quaternion() const;
  public:
  void clear_quaternion();
  const ::messaging::Quaternion_msg& quaternion() const;
  PROTOBUF_MUST_USE_RESULT ::messaging::Quaternion_msg* release_quaternion();
  ::messaging::Quaternion_msg* mutable_quaternion();
  void set_allocated_quaternion(::messaging::Quaternion_msg* quaternion);
  private:
  const ::messaging::Quaternion_msg& _internal_quaternion() const;
  ::messaging::Quaternion_msg* _internal_mutable_quaternion();
  public:
  void unsafe_arena_set_allocated_quaternion(
      ::messaging::Quaternion_msg* quaternion);
  ::messaging::Quaternion_msg* unsafe_arena_release_quaternion();

  // double time = 3;
  void clear_time();
  double time() const;
  void set_time(double value);
  private:
  double _internal_time() const;
  void _internal_set_time(double value);
  public:

  // @@protoc_insertion_point(class_scope:messaging.Vicon_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::messaging::Vector3_msg* position_;
  ::messaging::Quaternion_msg* quaternion_;
  double time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Vector3_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messaging.Vector3_msg) */ {
 public:
  inline Vector3_msg() : Vector3_msg(nullptr) {}
  ~Vector3_msg() override;
  explicit constexpr Vector3_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector3_msg(const Vector3_msg& from);
  Vector3_msg(Vector3_msg&& from) noexcept
    : Vector3_msg() {
    *this = ::std::move(from);
  }

  inline Vector3_msg& operator=(const Vector3_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3_msg& operator=(Vector3_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector3_msg* internal_default_instance() {
    return reinterpret_cast<const Vector3_msg*>(
               &_Vector3_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Vector3_msg& a, Vector3_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3_msg* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vector3_msg* New() const final {
    return new Vector3_msg();
  }

  Vector3_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vector3_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector3_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Vector3_msg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3_msg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messaging.Vector3_msg";
  }
  protected:
  explicit Vector3_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // double x = 1;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 2;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 3;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:messaging.Vector3_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double x_;
  double y_;
  double z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// -------------------------------------------------------------------

class Quaternion_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:messaging.Quaternion_msg) */ {
 public:
  inline Quaternion_msg() : Quaternion_msg(nullptr) {}
  ~Quaternion_msg() override;
  explicit constexpr Quaternion_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Quaternion_msg(const Quaternion_msg& from);
  Quaternion_msg(Quaternion_msg&& from) noexcept
    : Quaternion_msg() {
    *this = ::std::move(from);
  }

  inline Quaternion_msg& operator=(const Quaternion_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Quaternion_msg& operator=(Quaternion_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Quaternion_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const Quaternion_msg* internal_default_instance() {
    return reinterpret_cast<const Quaternion_msg*>(
               &_Quaternion_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Quaternion_msg& a, Quaternion_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(Quaternion_msg* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Quaternion_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Quaternion_msg* New() const final {
    return new Quaternion_msg();
  }

  Quaternion_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Quaternion_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Quaternion_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Quaternion_msg& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Quaternion_msg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "messaging.Quaternion_msg";
  }
  protected:
  explicit Quaternion_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kZFieldNumber = 4,
  };
  // double w = 1;
  void clear_w();
  double w() const;
  void set_w(double value);
  private:
  double _internal_w() const;
  void _internal_set_w(double value);
  public:

  // double x = 2;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 3;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 4;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:messaging.Quaternion_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double w_;
  double x_;
  double y_;
  double z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EKF_msg

// .messaging.Vector3_msg position = 1;
inline bool EKF_msg::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool EKF_msg::has_position() const {
  return _internal_has_position();
}
inline void EKF_msg::clear_position() {
  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::messaging::Vector3_msg& EKF_msg::_internal_position() const {
  const ::messaging::Vector3_msg* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Vector3_msg&>(
      ::messaging::_Vector3_msg_default_instance_);
}
inline const ::messaging::Vector3_msg& EKF_msg::position() const {
  // @@protoc_insertion_point(field_get:messaging.EKF_msg.position)
  return _internal_position();
}
inline void EKF_msg::unsafe_arena_set_allocated_position(
    ::messaging::Vector3_msg* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.EKF_msg.position)
}
inline ::messaging::Vector3_msg* EKF_msg::release_position() {
  
  ::messaging::Vector3_msg* temp = position_;
  position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:messaging.EKF_msg.position)
  
  ::messaging::Vector3_msg* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Vector3_msg>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::messaging::Vector3_msg* EKF_msg::mutable_position() {
  ::messaging::Vector3_msg* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:messaging.EKF_msg.position)
  return _msg;
}
inline void EKF_msg::set_allocated_position(::messaging::Vector3_msg* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Vector3_msg>::GetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:messaging.EKF_msg.position)
}

// .messaging.Quaternion_msg quaternion = 2;
inline bool EKF_msg::_internal_has_quaternion() const {
  return this != internal_default_instance() && quaternion_ != nullptr;
}
inline bool EKF_msg::has_quaternion() const {
  return _internal_has_quaternion();
}
inline void EKF_msg::clear_quaternion() {
  if (GetArenaForAllocation() == nullptr && quaternion_ != nullptr) {
    delete quaternion_;
  }
  quaternion_ = nullptr;
}
inline const ::messaging::Quaternion_msg& EKF_msg::_internal_quaternion() const {
  const ::messaging::Quaternion_msg* p = quaternion_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Quaternion_msg&>(
      ::messaging::_Quaternion_msg_default_instance_);
}
inline const ::messaging::Quaternion_msg& EKF_msg::quaternion() const {
  // @@protoc_insertion_point(field_get:messaging.EKF_msg.quaternion)
  return _internal_quaternion();
}
inline void EKF_msg::unsafe_arena_set_allocated_quaternion(
    ::messaging::Quaternion_msg* quaternion) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(quaternion_);
  }
  quaternion_ = quaternion;
  if (quaternion) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.EKF_msg.quaternion)
}
inline ::messaging::Quaternion_msg* EKF_msg::release_quaternion() {
  
  ::messaging::Quaternion_msg* temp = quaternion_;
  quaternion_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Quaternion_msg* EKF_msg::unsafe_arena_release_quaternion() {
  // @@protoc_insertion_point(field_release:messaging.EKF_msg.quaternion)
  
  ::messaging::Quaternion_msg* temp = quaternion_;
  quaternion_ = nullptr;
  return temp;
}
inline ::messaging::Quaternion_msg* EKF_msg::_internal_mutable_quaternion() {
  
  if (quaternion_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Quaternion_msg>(GetArenaForAllocation());
    quaternion_ = p;
  }
  return quaternion_;
}
inline ::messaging::Quaternion_msg* EKF_msg::mutable_quaternion() {
  ::messaging::Quaternion_msg* _msg = _internal_mutable_quaternion();
  // @@protoc_insertion_point(field_mutable:messaging.EKF_msg.quaternion)
  return _msg;
}
inline void EKF_msg::set_allocated_quaternion(::messaging::Quaternion_msg* quaternion) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete quaternion_;
  }
  if (quaternion) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Quaternion_msg>::GetOwningArena(quaternion);
    if (message_arena != submessage_arena) {
      quaternion = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, quaternion, submessage_arena);
    }
    
  } else {
    
  }
  quaternion_ = quaternion;
  // @@protoc_insertion_point(field_set_allocated:messaging.EKF_msg.quaternion)
}

// .messaging.Vector3_msg velocity = 3;
inline bool EKF_msg::_internal_has_velocity() const {
  return this != internal_default_instance() && velocity_ != nullptr;
}
inline bool EKF_msg::has_velocity() const {
  return _internal_has_velocity();
}
inline void EKF_msg::clear_velocity() {
  if (GetArenaForAllocation() == nullptr && velocity_ != nullptr) {
    delete velocity_;
  }
  velocity_ = nullptr;
}
inline const ::messaging::Vector3_msg& EKF_msg::_internal_velocity() const {
  const ::messaging::Vector3_msg* p = velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Vector3_msg&>(
      ::messaging::_Vector3_msg_default_instance_);
}
inline const ::messaging::Vector3_msg& EKF_msg::velocity() const {
  // @@protoc_insertion_point(field_get:messaging.EKF_msg.velocity)
  return _internal_velocity();
}
inline void EKF_msg::unsafe_arena_set_allocated_velocity(
    ::messaging::Vector3_msg* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity_);
  }
  velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.EKF_msg.velocity)
}
inline ::messaging::Vector3_msg* EKF_msg::release_velocity() {
  
  ::messaging::Vector3_msg* temp = velocity_;
  velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:messaging.EKF_msg.velocity)
  
  ::messaging::Vector3_msg* temp = velocity_;
  velocity_ = nullptr;
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::_internal_mutable_velocity() {
  
  if (velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Vector3_msg>(GetArenaForAllocation());
    velocity_ = p;
  }
  return velocity_;
}
inline ::messaging::Vector3_msg* EKF_msg::mutable_velocity() {
  ::messaging::Vector3_msg* _msg = _internal_mutable_velocity();
  // @@protoc_insertion_point(field_mutable:messaging.EKF_msg.velocity)
  return _msg;
}
inline void EKF_msg::set_allocated_velocity(::messaging::Vector3_msg* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete velocity_;
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Vector3_msg>::GetOwningArena(velocity);
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:messaging.EKF_msg.velocity)
}

// .messaging.Vector3_msg acceleration_bias = 4;
inline bool EKF_msg::_internal_has_acceleration_bias() const {
  return this != internal_default_instance() && acceleration_bias_ != nullptr;
}
inline bool EKF_msg::has_acceleration_bias() const {
  return _internal_has_acceleration_bias();
}
inline void EKF_msg::clear_acceleration_bias() {
  if (GetArenaForAllocation() == nullptr && acceleration_bias_ != nullptr) {
    delete acceleration_bias_;
  }
  acceleration_bias_ = nullptr;
}
inline const ::messaging::Vector3_msg& EKF_msg::_internal_acceleration_bias() const {
  const ::messaging::Vector3_msg* p = acceleration_bias_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Vector3_msg&>(
      ::messaging::_Vector3_msg_default_instance_);
}
inline const ::messaging::Vector3_msg& EKF_msg::acceleration_bias() const {
  // @@protoc_insertion_point(field_get:messaging.EKF_msg.acceleration_bias)
  return _internal_acceleration_bias();
}
inline void EKF_msg::unsafe_arena_set_allocated_acceleration_bias(
    ::messaging::Vector3_msg* acceleration_bias) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(acceleration_bias_);
  }
  acceleration_bias_ = acceleration_bias;
  if (acceleration_bias) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.EKF_msg.acceleration_bias)
}
inline ::messaging::Vector3_msg* EKF_msg::release_acceleration_bias() {
  
  ::messaging::Vector3_msg* temp = acceleration_bias_;
  acceleration_bias_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::unsafe_arena_release_acceleration_bias() {
  // @@protoc_insertion_point(field_release:messaging.EKF_msg.acceleration_bias)
  
  ::messaging::Vector3_msg* temp = acceleration_bias_;
  acceleration_bias_ = nullptr;
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::_internal_mutable_acceleration_bias() {
  
  if (acceleration_bias_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Vector3_msg>(GetArenaForAllocation());
    acceleration_bias_ = p;
  }
  return acceleration_bias_;
}
inline ::messaging::Vector3_msg* EKF_msg::mutable_acceleration_bias() {
  ::messaging::Vector3_msg* _msg = _internal_mutable_acceleration_bias();
  // @@protoc_insertion_point(field_mutable:messaging.EKF_msg.acceleration_bias)
  return _msg;
}
inline void EKF_msg::set_allocated_acceleration_bias(::messaging::Vector3_msg* acceleration_bias) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete acceleration_bias_;
  }
  if (acceleration_bias) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Vector3_msg>::GetOwningArena(acceleration_bias);
    if (message_arena != submessage_arena) {
      acceleration_bias = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, acceleration_bias, submessage_arena);
    }
    
  } else {
    
  }
  acceleration_bias_ = acceleration_bias;
  // @@protoc_insertion_point(field_set_allocated:messaging.EKF_msg.acceleration_bias)
}

// .messaging.Vector3_msg angular_velocity_bias = 5;
inline bool EKF_msg::_internal_has_angular_velocity_bias() const {
  return this != internal_default_instance() && angular_velocity_bias_ != nullptr;
}
inline bool EKF_msg::has_angular_velocity_bias() const {
  return _internal_has_angular_velocity_bias();
}
inline void EKF_msg::clear_angular_velocity_bias() {
  if (GetArenaForAllocation() == nullptr && angular_velocity_bias_ != nullptr) {
    delete angular_velocity_bias_;
  }
  angular_velocity_bias_ = nullptr;
}
inline const ::messaging::Vector3_msg& EKF_msg::_internal_angular_velocity_bias() const {
  const ::messaging::Vector3_msg* p = angular_velocity_bias_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Vector3_msg&>(
      ::messaging::_Vector3_msg_default_instance_);
}
inline const ::messaging::Vector3_msg& EKF_msg::angular_velocity_bias() const {
  // @@protoc_insertion_point(field_get:messaging.EKF_msg.angular_velocity_bias)
  return _internal_angular_velocity_bias();
}
inline void EKF_msg::unsafe_arena_set_allocated_angular_velocity_bias(
    ::messaging::Vector3_msg* angular_velocity_bias) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity_bias_);
  }
  angular_velocity_bias_ = angular_velocity_bias;
  if (angular_velocity_bias) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.EKF_msg.angular_velocity_bias)
}
inline ::messaging::Vector3_msg* EKF_msg::release_angular_velocity_bias() {
  
  ::messaging::Vector3_msg* temp = angular_velocity_bias_;
  angular_velocity_bias_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::unsafe_arena_release_angular_velocity_bias() {
  // @@protoc_insertion_point(field_release:messaging.EKF_msg.angular_velocity_bias)
  
  ::messaging::Vector3_msg* temp = angular_velocity_bias_;
  angular_velocity_bias_ = nullptr;
  return temp;
}
inline ::messaging::Vector3_msg* EKF_msg::_internal_mutable_angular_velocity_bias() {
  
  if (angular_velocity_bias_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Vector3_msg>(GetArenaForAllocation());
    angular_velocity_bias_ = p;
  }
  return angular_velocity_bias_;
}
inline ::messaging::Vector3_msg* EKF_msg::mutable_angular_velocity_bias() {
  ::messaging::Vector3_msg* _msg = _internal_mutable_angular_velocity_bias();
  // @@protoc_insertion_point(field_mutable:messaging.EKF_msg.angular_velocity_bias)
  return _msg;
}
inline void EKF_msg::set_allocated_angular_velocity_bias(::messaging::Vector3_msg* angular_velocity_bias) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete angular_velocity_bias_;
  }
  if (angular_velocity_bias) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Vector3_msg>::GetOwningArena(angular_velocity_bias);
    if (message_arena != submessage_arena) {
      angular_velocity_bias = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, angular_velocity_bias, submessage_arena);
    }
    
  } else {
    
  }
  angular_velocity_bias_ = angular_velocity_bias;
  // @@protoc_insertion_point(field_set_allocated:messaging.EKF_msg.angular_velocity_bias)
}

// double time = 6;
inline void EKF_msg::clear_time() {
  time_ = 0;
}
inline double EKF_msg::_internal_time() const {
  return time_;
}
inline double EKF_msg::time() const {
  // @@protoc_insertion_point(field_get:messaging.EKF_msg.time)
  return _internal_time();
}
inline void EKF_msg::_internal_set_time(double value) {
  
  time_ = value;
}
inline void EKF_msg::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:messaging.EKF_msg.time)
}

// -------------------------------------------------------------------

// IMU_msg

// .messaging.Vector3_msg acceleration = 1;
inline bool IMU_msg::_internal_has_acceleration() const {
  return this != internal_default_instance() && acceleration_ != nullptr;
}
inline bool IMU_msg::has_acceleration() const {
  return _internal_has_acceleration();
}
inline void IMU_msg::clear_acceleration() {
  if (GetArenaForAllocation() == nullptr && acceleration_ != nullptr) {
    delete acceleration_;
  }
  acceleration_ = nullptr;
}
inline const ::messaging::Vector3_msg& IMU_msg::_internal_acceleration() const {
  const ::messaging::Vector3_msg* p = acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Vector3_msg&>(
      ::messaging::_Vector3_msg_default_instance_);
}
inline const ::messaging::Vector3_msg& IMU_msg::acceleration() const {
  // @@protoc_insertion_point(field_get:messaging.IMU_msg.acceleration)
  return _internal_acceleration();
}
inline void IMU_msg::unsafe_arena_set_allocated_acceleration(
    ::messaging::Vector3_msg* acceleration) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(acceleration_);
  }
  acceleration_ = acceleration;
  if (acceleration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.IMU_msg.acceleration)
}
inline ::messaging::Vector3_msg* IMU_msg::release_acceleration() {
  
  ::messaging::Vector3_msg* temp = acceleration_;
  acceleration_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Vector3_msg* IMU_msg::unsafe_arena_release_acceleration() {
  // @@protoc_insertion_point(field_release:messaging.IMU_msg.acceleration)
  
  ::messaging::Vector3_msg* temp = acceleration_;
  acceleration_ = nullptr;
  return temp;
}
inline ::messaging::Vector3_msg* IMU_msg::_internal_mutable_acceleration() {
  
  if (acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Vector3_msg>(GetArenaForAllocation());
    acceleration_ = p;
  }
  return acceleration_;
}
inline ::messaging::Vector3_msg* IMU_msg::mutable_acceleration() {
  ::messaging::Vector3_msg* _msg = _internal_mutable_acceleration();
  // @@protoc_insertion_point(field_mutable:messaging.IMU_msg.acceleration)
  return _msg;
}
inline void IMU_msg::set_allocated_acceleration(::messaging::Vector3_msg* acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete acceleration_;
  }
  if (acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Vector3_msg>::GetOwningArena(acceleration);
    if (message_arena != submessage_arena) {
      acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, acceleration, submessage_arena);
    }
    
  } else {
    
  }
  acceleration_ = acceleration;
  // @@protoc_insertion_point(field_set_allocated:messaging.IMU_msg.acceleration)
}

// .messaging.Vector3_msg gyroscope = 2;
inline bool IMU_msg::_internal_has_gyroscope() const {
  return this != internal_default_instance() && gyroscope_ != nullptr;
}
inline bool IMU_msg::has_gyroscope() const {
  return _internal_has_gyroscope();
}
inline void IMU_msg::clear_gyroscope() {
  if (GetArenaForAllocation() == nullptr && gyroscope_ != nullptr) {
    delete gyroscope_;
  }
  gyroscope_ = nullptr;
}
inline const ::messaging::Vector3_msg& IMU_msg::_internal_gyroscope() const {
  const ::messaging::Vector3_msg* p = gyroscope_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Vector3_msg&>(
      ::messaging::_Vector3_msg_default_instance_);
}
inline const ::messaging::Vector3_msg& IMU_msg::gyroscope() const {
  // @@protoc_insertion_point(field_get:messaging.IMU_msg.gyroscope)
  return _internal_gyroscope();
}
inline void IMU_msg::unsafe_arena_set_allocated_gyroscope(
    ::messaging::Vector3_msg* gyroscope) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(gyroscope_);
  }
  gyroscope_ = gyroscope;
  if (gyroscope) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.IMU_msg.gyroscope)
}
inline ::messaging::Vector3_msg* IMU_msg::release_gyroscope() {
  
  ::messaging::Vector3_msg* temp = gyroscope_;
  gyroscope_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Vector3_msg* IMU_msg::unsafe_arena_release_gyroscope() {
  // @@protoc_insertion_point(field_release:messaging.IMU_msg.gyroscope)
  
  ::messaging::Vector3_msg* temp = gyroscope_;
  gyroscope_ = nullptr;
  return temp;
}
inline ::messaging::Vector3_msg* IMU_msg::_internal_mutable_gyroscope() {
  
  if (gyroscope_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Vector3_msg>(GetArenaForAllocation());
    gyroscope_ = p;
  }
  return gyroscope_;
}
inline ::messaging::Vector3_msg* IMU_msg::mutable_gyroscope() {
  ::messaging::Vector3_msg* _msg = _internal_mutable_gyroscope();
  // @@protoc_insertion_point(field_mutable:messaging.IMU_msg.gyroscope)
  return _msg;
}
inline void IMU_msg::set_allocated_gyroscope(::messaging::Vector3_msg* gyroscope) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete gyroscope_;
  }
  if (gyroscope) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Vector3_msg>::GetOwningArena(gyroscope);
    if (message_arena != submessage_arena) {
      gyroscope = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gyroscope, submessage_arena);
    }
    
  } else {
    
  }
  gyroscope_ = gyroscope;
  // @@protoc_insertion_point(field_set_allocated:messaging.IMU_msg.gyroscope)
}

// double time = 3;
inline void IMU_msg::clear_time() {
  time_ = 0;
}
inline double IMU_msg::_internal_time() const {
  return time_;
}
inline double IMU_msg::time() const {
  // @@protoc_insertion_point(field_get:messaging.IMU_msg.time)
  return _internal_time();
}
inline void IMU_msg::_internal_set_time(double value) {
  
  time_ = value;
}
inline void IMU_msg::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:messaging.IMU_msg.time)
}

// -------------------------------------------------------------------

// Vicon_msg

// .messaging.Vector3_msg position = 1;
inline bool Vicon_msg::_internal_has_position() const {
  return this != internal_default_instance() && position_ != nullptr;
}
inline bool Vicon_msg::has_position() const {
  return _internal_has_position();
}
inline void Vicon_msg::clear_position() {
  if (GetArenaForAllocation() == nullptr && position_ != nullptr) {
    delete position_;
  }
  position_ = nullptr;
}
inline const ::messaging::Vector3_msg& Vicon_msg::_internal_position() const {
  const ::messaging::Vector3_msg* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Vector3_msg&>(
      ::messaging::_Vector3_msg_default_instance_);
}
inline const ::messaging::Vector3_msg& Vicon_msg::position() const {
  // @@protoc_insertion_point(field_get:messaging.Vicon_msg.position)
  return _internal_position();
}
inline void Vicon_msg::unsafe_arena_set_allocated_position(
    ::messaging::Vector3_msg* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.Vicon_msg.position)
}
inline ::messaging::Vector3_msg* Vicon_msg::release_position() {
  
  ::messaging::Vector3_msg* temp = position_;
  position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Vector3_msg* Vicon_msg::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:messaging.Vicon_msg.position)
  
  ::messaging::Vector3_msg* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::messaging::Vector3_msg* Vicon_msg::_internal_mutable_position() {
  
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Vector3_msg>(GetArenaForAllocation());
    position_ = p;
  }
  return position_;
}
inline ::messaging::Vector3_msg* Vicon_msg::mutable_position() {
  ::messaging::Vector3_msg* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:messaging.Vicon_msg.position)
  return _msg;
}
inline void Vicon_msg::set_allocated_position(::messaging::Vector3_msg* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete position_;
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Vector3_msg>::GetOwningArena(position);
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:messaging.Vicon_msg.position)
}

// .messaging.Quaternion_msg quaternion = 2;
inline bool Vicon_msg::_internal_has_quaternion() const {
  return this != internal_default_instance() && quaternion_ != nullptr;
}
inline bool Vicon_msg::has_quaternion() const {
  return _internal_has_quaternion();
}
inline void Vicon_msg::clear_quaternion() {
  if (GetArenaForAllocation() == nullptr && quaternion_ != nullptr) {
    delete quaternion_;
  }
  quaternion_ = nullptr;
}
inline const ::messaging::Quaternion_msg& Vicon_msg::_internal_quaternion() const {
  const ::messaging::Quaternion_msg* p = quaternion_;
  return p != nullptr ? *p : reinterpret_cast<const ::messaging::Quaternion_msg&>(
      ::messaging::_Quaternion_msg_default_instance_);
}
inline const ::messaging::Quaternion_msg& Vicon_msg::quaternion() const {
  // @@protoc_insertion_point(field_get:messaging.Vicon_msg.quaternion)
  return _internal_quaternion();
}
inline void Vicon_msg::unsafe_arena_set_allocated_quaternion(
    ::messaging::Quaternion_msg* quaternion) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(quaternion_);
  }
  quaternion_ = quaternion;
  if (quaternion) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:messaging.Vicon_msg.quaternion)
}
inline ::messaging::Quaternion_msg* Vicon_msg::release_quaternion() {
  
  ::messaging::Quaternion_msg* temp = quaternion_;
  quaternion_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::messaging::Quaternion_msg* Vicon_msg::unsafe_arena_release_quaternion() {
  // @@protoc_insertion_point(field_release:messaging.Vicon_msg.quaternion)
  
  ::messaging::Quaternion_msg* temp = quaternion_;
  quaternion_ = nullptr;
  return temp;
}
inline ::messaging::Quaternion_msg* Vicon_msg::_internal_mutable_quaternion() {
  
  if (quaternion_ == nullptr) {
    auto* p = CreateMaybeMessage<::messaging::Quaternion_msg>(GetArenaForAllocation());
    quaternion_ = p;
  }
  return quaternion_;
}
inline ::messaging::Quaternion_msg* Vicon_msg::mutable_quaternion() {
  ::messaging::Quaternion_msg* _msg = _internal_mutable_quaternion();
  // @@protoc_insertion_point(field_mutable:messaging.Vicon_msg.quaternion)
  return _msg;
}
inline void Vicon_msg::set_allocated_quaternion(::messaging::Quaternion_msg* quaternion) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete quaternion_;
  }
  if (quaternion) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::messaging::Quaternion_msg>::GetOwningArena(quaternion);
    if (message_arena != submessage_arena) {
      quaternion = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, quaternion, submessage_arena);
    }
    
  } else {
    
  }
  quaternion_ = quaternion;
  // @@protoc_insertion_point(field_set_allocated:messaging.Vicon_msg.quaternion)
}

// double time = 3;
inline void Vicon_msg::clear_time() {
  time_ = 0;
}
inline double Vicon_msg::_internal_time() const {
  return time_;
}
inline double Vicon_msg::time() const {
  // @@protoc_insertion_point(field_get:messaging.Vicon_msg.time)
  return _internal_time();
}
inline void Vicon_msg::_internal_set_time(double value) {
  
  time_ = value;
}
inline void Vicon_msg::set_time(double value) {
  _internal_set_time(value);
  // @@protoc_insertion_point(field_set:messaging.Vicon_msg.time)
}

// -------------------------------------------------------------------

// Vector3_msg

// double x = 1;
inline void Vector3_msg::clear_x() {
  x_ = 0;
}
inline double Vector3_msg::_internal_x() const {
  return x_;
}
inline double Vector3_msg::x() const {
  // @@protoc_insertion_point(field_get:messaging.Vector3_msg.x)
  return _internal_x();
}
inline void Vector3_msg::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Vector3_msg::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:messaging.Vector3_msg.x)
}

// double y = 2;
inline void Vector3_msg::clear_y() {
  y_ = 0;
}
inline double Vector3_msg::_internal_y() const {
  return y_;
}
inline double Vector3_msg::y() const {
  // @@protoc_insertion_point(field_get:messaging.Vector3_msg.y)
  return _internal_y();
}
inline void Vector3_msg::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Vector3_msg::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:messaging.Vector3_msg.y)
}

// double z = 3;
inline void Vector3_msg::clear_z() {
  z_ = 0;
}
inline double Vector3_msg::_internal_z() const {
  return z_;
}
inline double Vector3_msg::z() const {
  // @@protoc_insertion_point(field_get:messaging.Vector3_msg.z)
  return _internal_z();
}
inline void Vector3_msg::_internal_set_z(double value) {
  
  z_ = value;
}
inline void Vector3_msg::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:messaging.Vector3_msg.z)
}

// -------------------------------------------------------------------

// Quaternion_msg

// double w = 1;
inline void Quaternion_msg::clear_w() {
  w_ = 0;
}
inline double Quaternion_msg::_internal_w() const {
  return w_;
}
inline double Quaternion_msg::w() const {
  // @@protoc_insertion_point(field_get:messaging.Quaternion_msg.w)
  return _internal_w();
}
inline void Quaternion_msg::_internal_set_w(double value) {
  
  w_ = value;
}
inline void Quaternion_msg::set_w(double value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:messaging.Quaternion_msg.w)
}

// double x = 2;
inline void Quaternion_msg::clear_x() {
  x_ = 0;
}
inline double Quaternion_msg::_internal_x() const {
  return x_;
}
inline double Quaternion_msg::x() const {
  // @@protoc_insertion_point(field_get:messaging.Quaternion_msg.x)
  return _internal_x();
}
inline void Quaternion_msg::_internal_set_x(double value) {
  
  x_ = value;
}
inline void Quaternion_msg::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:messaging.Quaternion_msg.x)
}

// double y = 3;
inline void Quaternion_msg::clear_y() {
  y_ = 0;
}
inline double Quaternion_msg::_internal_y() const {
  return y_;
}
inline double Quaternion_msg::y() const {
  // @@protoc_insertion_point(field_get:messaging.Quaternion_msg.y)
  return _internal_y();
}
inline void Quaternion_msg::_internal_set_y(double value) {
  
  y_ = value;
}
inline void Quaternion_msg::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:messaging.Quaternion_msg.y)
}

// double z = 4;
inline void Quaternion_msg::clear_z() {
  z_ = 0;
}
inline double Quaternion_msg::_internal_z() const {
  return z_;
}
inline double Quaternion_msg::z() const {
  // @@protoc_insertion_point(field_get:messaging.Quaternion_msg.z)
  return _internal_z();
}
inline void Quaternion_msg::_internal_set_z(double value) {
  
  z_ = value;
}
inline void Quaternion_msg::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:messaging.Quaternion_msg.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace messaging

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_message_2eproto
